export const CREATE_TRANSACTION = "CREATE_TRANSACTION";

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";

export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const UPDATE_WALLET_BALANCE = "UPDATE_WALLET_BALANCE";
